# Site settings
title: People Analyst
baseurl: ""
url: "https://github.com/camarn/crispy-memory"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Cameron Arno
  desc: M.S. I/O Psychology '22 | Texas A&M University
  email: cameron.arno@gmail.com
  selfie: assets/img/Cameron2.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  github: camarn
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/cameron-arno-1633861ba/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter:
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
